### ISSUE TITLE
Linux-x64 build is broken / insufficient documentation.

### ISSUE THREAD

**Issue by awochna** [Musicoin/desktop#20]
Instructions say to just start Musicoin: `./Musicoin-client`, but that file is initially not executable. After making the file executable, the following output is generated:

```
process.platform: linux
process.env.APPDATA: undefined
process.env.HOME: /home/awynter
Initializing command: {"name":"Musicoin - Pi","path":"{process.cwd}/bin/go-musicoin/","command":"./gmc","args":["--rpc","--rpcapi=admin,db,eth,net,web3,personal,miner","--rpcport","8545","--rpcaddr","127.0.0.1","--rpccorsdomain","localhost"],"rpcServer":"http://localhost:8545"}
Initialized command: {"name":"Musicoin - Pi","path":"{process.cwd}/bin/go-musicoin/","command":"./gmc","args":["--rpc","--rpcapi=admin,db,eth,net,web3,personal,miner","--rpcport","8545","--rpcaddr","127.0.0.1","--rpccorsdomain","localhost"],"rpcServer":"http://localhost:8545","absolutePath":"/home/awynter/Downloads/Musicoin-client-linux-x64/bin/go-musicoin/"}
Starting Musicoin - Pi: ./gmc, args: [--rpc,--rpcapi=admin,db,eth,net,web3,personal,miner,--rpcport,8545,--rpcaddr,127.0.0.1,--rpccorsdomain,localhost], cwd: /home/awynter/Downloads/Musicoin-client-linux-x64/bin/go-musicoin/
internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1023:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:387:9)
    at Startup.execAndKillOnShutdown (/home/awynter/Downloads/Musicoin-client-linux-x64/hub/startup.js:23:29)
    at Startup.startChildProcess (/home/awynter/Downloads/Musicoin-client-linux-x64/hub/startup.js:54:8)
    at Object.<anonymous> (/home/awynter/Downloads/Musicoin-client-linux-x64/hub/msc.js:43:37)
    at Module._compile (module.js:595:32)
    at Object.Module._extensions..js (module.js:610:10)
    at Module.load (module.js:512:32)
    at tryModuleLoad (module.js:471:12)
    at Function.Module._load (module.js:463:3)
    at Function.Module.runMain (module.js:647:10)
    at startup (bootstrap_node.js:75:16)
    at bootstrap_node.js:541:3
chrome-extension://henghicddkekjknhlmllmjijioddpfcm/interface/elements/msc-element/msc-element.js:25
          value: mscIntf.lang,
                        ^

TypeError: Cannot read property 'lang' of undefined
    at chrome-extension://henghicddkekjknhlmllmjijioddpfcm/interface/elements/msc-element/msc-element.js:25:25
chrome-extension://henghicddkekjknhlmllmjijioddpfcm/interface/elements/msc-element/msc-element.html:48
      var logDir = mscIntf.clientUtils.getLogDir();
                          ^

TypeError: Cannot read property 'clientUtils' of undefined
    at setupDebugLogging (chrome-extension://henghicddkekjknhlmllmjijioddpfcm/interface/elements/msc-element/msc-element.html:48:27)
    at chrome-extension://henghicddkekjknhlmllmjijioddpfcm/interface/elements/msc-element/msc-element.html:62:5
```

Helpfully, there is a `linux-setup.sh` file that looks like it's supposed to make sure we install prerequisites and make certain files executable, including `Musicoin-client`. Unfortunately, this file is not executable by default. After making it executable and running it, we get:

```
./linux-setup.sh: bad interpreter: /bin/bash^M: no such file or directory
```

This is because this file uses dos line endings (CRLF) and not unix line endings (LF). Converting line endings to unix allows the file to execute, but:

```
chmod: cannot access 'bin/geth/geth': No such file or directory
chmod: cannot access 'bin/go-ipfs/ipfs': No such file or directory
```

It can't find the `geth` or `ipfs` executables because they don't exist. A quick run of `find` also shows that they don't exist in a different folder.

**Comment by immartian** [comment]
Did you try to 
```sudo chmod +x bin/go-musicoin/gmc
sudo chmod +x Musicoin-client``` 

before running up the client?  I'm sure you chmod to `Musicoin-client` already as it can run such output, but `gmc` is also necessary to run up upfront. 

Somewhat there could be some other errors but may have little different make sure gmc running up.

**Comment by awochna** [comment]
@immartian Thanks for your reply!

After making `gmc` executable, it seems everything is working. Is that all that should be in this package, though? Should the references to `geth` and `go-ipfs` be removed from the `linux-setup.sh` and should `chmod + x bin/go-musicoin/gmc` be added? Should we update the website documentation for the wallet to show the proper steps?

I would love to help, just point me in the right direction.

**Comment by immartian** [comment]
Thanks @awochna , just Pull Request a change, if you fill confident about the solution.

**Comment by Varunram** [comment]
@awochna I've just made a change to `go-musicoin` under which `gmc` is housed. I will remove references to `geth` and `go-ipfs` from the script. Thanks for pointing out!
