### ISSUE TITLE
can't run npm install

### ISSUE THREAD

**Issue by bernardoaraujor** [Musicoin/desktop#48]
I'm on ubuntu 14.04.

This is the end of the log, after running npm install:

...
```npm http 200 https://registry.npmjs.org/number-is-nan
npm http GET https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.1.tgz
npm http 200 https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.1.tgz

> keccak@1.3.0 install /home/bernardo/musicoin-desktop/node_modules/eth-lightwallet-nwjs/node_modules/ethereumjs-tx/node_modules/ethereumjs-util/node_modules/keccak
> prebuild-install || node-gyp rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."

/usr/bin/env: node: No such file or directory
/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.4.0-93-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/bernardo/musicoin-desktop/node_modules/eth-lightwallet-nwjs/node_modules/ethereumjs-tx/node_modules/ethereumjs-util/node_modules/keccak
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
Keccak bindings compilation fail. Pure JS implementation will be used.
npm http GET https://registry.npmjs.org/loose-envify
npm http GET https://registry.npmjs.org/js-tokens
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/source-map-support
npm http GET https://registry.npmjs.org/home-or-tmp
npm http GET https://registry.npmjs.org/brace-expansion
npm http GET https://registry.npmjs.org/babylon
npm http 200 https://registry.npmjs.org/loose-envify
npm http 200 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/babylon
npm http 200 https://registry.npmjs.org/brace-expansion
npm http GET https://registry.npmjs.org/loose-envify/-/loose-envify-1.3.1.tgz
npm http GET https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz
npm http 200 https://registry.npmjs.org/home-or-tmp
npm http GET https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.8.tgz
npm http GET https://registry.npmjs.org/ms/2.0.0
npm http GET https://registry.npmjs.org/home-or-tmp/-/home-or-tmp-2.0.0.tgz
npm http 200 https://registry.npmjs.org/loose-envify/-/loose-envify-1.3.1.tgz
npm http 200 https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz
npm http 200 https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.8.tgz
npm http 200 https://registry.npmjs.org/home-or-tmp/-/home-or-tmp-2.0.0.tgz
npm http GET https://registry.npmjs.org/detect-indent
npm http GET https://registry.npmjs.org/trim-right
npm http GET https://registry.npmjs.org/jsesc/-/jsesc-1.3.0.tgz
npm http GET https://registry.npmjs.org/regenerator-runtime
npm http 200 https://registry.npmjs.org/js-tokens
npm http 304 https://registry.npmjs.org/regenerator-runtime
npm http GET https://registry.npmjs.org/js-tokens/-/js-tokens-3.0.2.tgz
npm http 200 https://registry.npmjs.org/jsesc/-/jsesc-1.3.0.tgz
npm http 200 https://registry.npmjs.org/js-tokens/-/js-tokens-3.0.2.tgz
npm http 200 https://registry.npmjs.org/trim-right
npm http 200 https://registry.npmjs.org/source-map-support
npm http GET https://registry.npmjs.org/trim-right/-/trim-right-1.0.1.tgz
npm http GET https://registry.npmjs.org/source-map-support/-/source-map-support-0.4.18.tgz
npm http GET https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/concat-map/0.0.1
npm http 200 https://registry.npmjs.org/trim-right/-/trim-right-1.0.1.tgz
npm http 200 https://registry.npmjs.org/detect-indent
npm http 200 https://registry.npmjs.org/source-map-support/-/source-map-support-0.4.18.tgz
npm http 200 https://registry.npmjs.org/concat-map/0.0.1
npm http 200 https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/detect-indent/-/detect-indent-4.0.0.tgz
npm http GET https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz
npm http GET https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz
npm http 200 https://registry.npmjs.org/detect-indent/-/detect-indent-4.0.0.tgz
npm http GET https://registry.npmjs.org/has-ansi
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/escape-string-regexp
npm http GET https://registry.npmjs.org/supports-color
npm http 200 https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz
npm http 200 https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz
npm http 200 https://registry.npmjs.org/escape-string-regexp
npm http GET https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz
npm http 200 https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz
npm http 200 https://registry.npmjs.org/ms/2.0.0
npm http 200 https://registry.npmjs.org/has-ansi
npm http 200 https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/ms/-/ms-2.0.0.tgz
npm http 200 https://registry.npmjs.org/supports-color
npm http GET https://registry.npmjs.org/to-fast-properties
npm http GET https://registry.npmjs.org/esutils
npm http GET https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz
npm http GET https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz
npm http GET https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz
npm http 200 https://registry.npmjs.org/ms/-/ms-2.0.0.tgz
npm http 304 https://registry.npmjs.org/esutils
npm http 304 https://registry.npmjs.org/to-fast-properties
npm http 200 https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz
npm http 200 https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz
npm http 200 https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz
npm http GET https://registry.npmjs.org/repeating
npm http GET https://registry.npmjs.org/debug
npm http 200 https://registry.npmjs.org/repeating
npm http GET https://registry.npmjs.org/babel-code-frame
npm http GET https://registry.npmjs.org/repeating/-/repeating-2.0.1.tgz
npm http 304 https://registry.npmjs.org/babel-code-frame
npm http 304 https://registry.npmjs.org/debug
npm http 200 https://registry.npmjs.org/repeating/-/repeating-2.0.1.tgz
npm http GET https://registry.npmjs.org/is-finite
npm http 200 https://registry.npmjs.org/is-finite
npm http GET https://registry.npmjs.org/is-finite/-/is-finite-1.0.2.tgz
npm http GET https://registry.npmjs.org/globals
npm http 200 https://registry.npmjs.org/is-finite/-/is-finite-1.0.2.tgz
npm http GET https://registry.npmjs.org/invariant
npm http 304 https://registry.npmjs.org/globals
npm http 304 https://registry.npmjs.org/invariant
npm http GET https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/babel-messages
npm http 304 https://registry.npmjs.org/babel-messages
npm http GET https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/ansi-regex
npm http GET https://registry.npmjs.org/os-homedir
npm http GET https://registry.npmjs.org/os-tmpdir
npm http 304 https://registry.npmjs.org/os-homedir
npm http 304 https://registry.npmjs.org/os-tmpdir
npm http GET https://registry.npmjs.org/core-js
npm http 304 https://registry.npmjs.org/core-js
npm http GET https://registry.npmjs.org/regenerator-runtime
npm http 304 https://registry.npmjs.org/regenerator-runtime

> secp256k1@3.2.2 install /home/bernardo/musicoin-desktop/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."


> secp256k1@3.2.2 rebuild /home/bernardo/musicoin-desktop/node_modules/secp256k1
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.4.0-93-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/bernardo/musicoin-desktop/node_modules/secp256k1
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
Secp256k1 bindings compilation fail. Pure JS implementation will be used.

> sha3@1.2.0 install /home/bernardo/musicoin-desktop/node_modules/sha3
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.4.0-93-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/bernardo/musicoin-desktop/node_modules/sha3
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
```

**Comment by Varunram** [comment]
This line `/bin/sh: 1: node: not found` shows that you either don't have node installed on your system or you haven't created a symlink to node (or that something weird has happened with the symlink itself). Please check your installation of node and update on this thread. Thanks!

**Comment by bernardoaraujor** [comment]
Hey @Varunram, thanks for the quick response!
I installed node, but still nothing happens :(

```
bernardo@bernardo-ThinkCentre-Edge72:~$ sudo apt-get install node
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libav-tools libavdevice53 libavfilter3 libmysqlclient18
  linux-headers-4.4.0-31 linux-headers-4.4.0-31-generic
  linux-image-4.4.0-31-generic linux-image-extra-4.4.0-31-generic mysql-common
  rtmpdump
Use 'apt-get autoremove' to remove them.
The following NEW packages will be installed:
  node
0 upgraded, 1 newly installed, 0 to remove and 35 not upgraded.
Need to get 0 B/1.284 B of archives.
After this operation, 38,9 kB of additional disk space will be used.
Selecting previously unselected package node.
(Reading database ... 413120 files and directories currently installed.)
Preparing to unpack .../node_0.3.2-7.4_all.deb ...
Unpacking node (0.3.2-7.4) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up node (0.3.2-7.4) ...
bernardo@bernardo-ThinkCentre-Edge72:~$ node
bernardo@bernardo-ThinkCentre-Edge72:~$ node --version
bernardo@bernardo-ThinkCentre-Edge72:~$ npm install
npm ERR! install Couldn't read dependencies
npm ERR! Error: ENOENT, open '/home/bernardo/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-93-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/bernardo
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/bernardo/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/bernardo/npm-debug.log
npm ERR! not ok code 0
```

**Comment by Varunram** [comment]
Hey! I think that nam is opening the file over at `/home/bernardo/package.json` instead of the one at `/home/bernardo/desktop/package.json`.

**Comment by bernardoaraujor** [comment]
How do I fix that?

**Comment by bernardoaraujor** [comment]
I think I had a legacy version of Node, which was installed by aptitude.
I used nvm to get node 5.0, and now npm install seems to be working. Thanks!
